// Late — leaderboard rules on the server. A submission is only the board
// (daily-YYYY-MM-DD), the generator version and the list of key presses.
// The Worker regenerates that day from its seed with the game's own
// generator (src/core, bundled by wrangler) and replays the key presses in
// the game's own simulation; the arrival time comes from that replay, never
// from the client.
import Late from '../../src/core/index.js';

export const MAX_SCORE_BODY_BYTES = 64 * 1024;
const BOARD_RE = /^daily-(\d{4})-(\d{2})-(\d{2})$/;
const NICKNAME_MIN = 2;
const NICKNAME_MAX = 20;
const BLOCKED = ['admin', 'moderator', 'fuck', 'shit', 'nigger', 'cunt'];

const reject = (code, error, status = 400) => ({ ok: false, code, error, status });

/** The seed and parameters every player of a daily board gets (Wednesday-level, no Director). */
export function boardDay(board) {
  const m = BOARD_RE.exec(board || '');
  if (!m) return null;
  return { seed: `DAILY-${m[1]}-${m[2]}-${m[3]}`, params: Late.difficulty.paramsFor(2), date: `${m[1]}-${m[2]}-${m[3]}` };
}

// Generating a day costs 20-100 ms of CPU; replaying one costs under 5 ms.
// Every player of a board shares the day, so keep it per isolate.
const cache = new Map();
export function dayFor(board) {
  if (cache.has(board)) return cache.get(board);
  const b = boardDay(board);
  const day = Late.day.generateDay(b.seed, b.params);
  cache.set(board, day);
  if (cache.size > 8) cache.delete(cache.keys().next().value);
  return day;
}

export function cleanNickname(raw) {
  if (typeof raw !== 'string') return reject('bad-nickname', 'Pick a nickname.');
  if (/[<>&"'`/\\]/.test(raw)) return reject('bad-nickname', 'No HTML or symbols in the nickname, please.');
  const name = raw.normalize('NFC').replace(/\s+/g, ' ').trim();
  const length = [...name].length;
  if (length < NICKNAME_MIN || length > NICKNAME_MAX) return reject('bad-nickname', `Use ${NICKNAME_MIN} to ${NICKNAME_MAX} characters.`);
  if (!/^[\p{L}\p{M}\p{Nd} _-]+$/u.test(name)) return reject('bad-nickname', 'Letters, digits, spaces, _ and - only.');
  if (!/[\p{L}\p{Nd}]/u.test(name)) return reject('bad-nickname', 'Use at least one letter or digit.');
  const lower = name.toLowerCase();
  if (BLOCKED.some((w) => lower.includes(w))) return reject('bad-nickname', 'Please pick a different nickname.');
  return { ok: true, nickname: name };
}

/**
 * @param sub {board, genVersion, inputs: [[tick, mask], ...]}
 * @param now Date, to refuse boards far from today
 */
export function replaySubmission(sub, now = new Date()) {
  if (!sub || typeof sub !== 'object' || Array.isArray(sub)) return reject('bad-body', 'Expected a JSON object.');
  const b = boardDay(sub.board);
  if (!b) return reject('bad-board', 'Unknown board.');
  const days = Math.abs(Date.parse(`${b.date}T00:00:00Z`) - now.getTime()) / 86400000;
  if (!(days <= 3)) return reject('closed-board', 'That daily board is closed.');
  if (sub.genVersion !== Late.day.GEN_VERSION) return reject('stale-generator', `This day was generated by ${String(sub.genVersion).slice(0, 12)}; the board ranks ${Late.day.GEN_VERSION} only.`, 409);
  if (!Late.sim.validInputs(sub.inputs)) return reject('bad-inputs', 'The key presses are malformed.');
  const day = dayFor(sub.board);
  const state = Late.sim.replay(day, sub.inputs);
  if (!state.result || state.result.how !== 'office') return reject('not-arrived', 'That replay never reaches the office.', 422);
  return { ok: true, board: sub.board, seed: day.seed, arrival: state.result.arrival, margin: state.result.margin, ticks: state.tick, fares: state.fares };
}

/** Higher margin (earlier arrival) is better; ties go to whoever set it first. */
export function compareScores(a, b) {
  if (a.margin !== b.margin) return b.margin - a.margin;
  if (a.createdAt !== b.createdAt) return a.createdAt < b.createdAt ? -1 : 1;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}
