// Cave Diving: leaderboard rules on the server. A submission is only the
// board (daily-YYYY-MM-DD), its seed, level and map setting, the generator
// version and the list of inputs. The Worker regenerates that day's maze
// with the game's own generator (src/gen.js, bundled by wrangler) and
// replays the inputs in the game's own simulation (src/game.js). The gas
// left and the dive time come from that replay, never from the client.
import Gen from '../../src/gen.js';
import GameModule from '../../src/game.js';
import Daily from '../../src/daily.js';

const { Game, STEP } = GameModule;

export const MAX_SCORE_BODY_BYTES = 512 * 1024;
export const GEN_VERSION = Gen.GEN_VERSION;
const NICKNAME_MIN = 2;
const NICKNAME_MAX = 20;
const BLOCKED = ['admin', 'moderator', 'fuck', 'shit', 'nigger', 'cunt'];

const reject = (code, error, status = 400) => ({ ok: false, code, error, status });

// Generating a daily maze costs 20-60 ms of CPU. Every player of a board
// dives the same maze, so keep it per isolate.
const cache = new Map();
export function diveFor(board) {
  if (cache.has(board)) return cache.get(board);
  const b = Daily.parse(board);
  const dive = Gen.generate(b.seed, b.level);
  cache.set(board, dive);
  if (cache.size > 8) cache.delete(cache.keys().next().value);
  return dive;
}

export function cleanNickname(raw) {
  if (typeof raw !== 'string') return reject('bad-nickname', 'Pick a nickname.');
  if (/[<>&"'`/\\]/.test(raw)) return reject('bad-nickname', 'No HTML or symbols in the nickname, please.');
  const name = raw.normalize('NFC').replace(/\s+/g, ' ').trim();
  const length = [...name].length;
  if (length < NICKNAME_MIN || length > NICKNAME_MAX) return reject('bad-nickname', `Use ${NICKNAME_MIN} to ${NICKNAME_MAX} characters.`);
  if (!/^[\p{L}\p{M}\p{Nd} _-]+$/u.test(name)) return reject('bad-nickname', 'Letters, digits, spaces, _ and - only.');
  if (!/[\p{L}\p{Nd}]/u.test(name)) return reject('bad-nickname', 'Use at least one letter or digit.');
  const lower = name.toLowerCase();
  if (BLOCKED.some((w) => lower.includes(w))) return reject('bad-nickname', 'Please pick a different nickname.');
  return { ok: true, nickname: name };
}

/**
 * @param sub {board, seed, level, mapMode, genVersion, inputs: [[tick, mask], ...]}
 * @param now Date, to refuse boards far from today
 */
export function replaySubmission(sub, now = new Date()) {
  if (!sub || typeof sub !== 'object' || Array.isArray(sub)) return reject('bad-body', 'Expected a JSON object.');
  const b = Daily.parse(sub.board);
  if (!b) return reject('bad-board', 'Unknown board.');
  const days = Math.abs(Date.parse(`${b.date}T00:00:00Z`) - now.getTime()) / 86400000;
  if (!(days <= 3)) return reject('closed-board', 'That daily board is closed.');
  if (sub.genVersion !== GEN_VERSION) return reject('stale-generator', `This maze was generated by ${String(sub.genVersion).slice(0, 12)}; the board ranks ${GEN_VERSION} only.`, 409);
  if (sub.seed !== b.seed || sub.level !== b.level || sub.mapMode !== b.mapMode) {
    return reject('bad-settings', `The daily board is seed ${b.seed}, level ${b.level}, map "${b.mapMode}".`);
  }
  if (!Game.validInputs(sub.inputs)) return reject('bad-inputs', 'The inputs are malformed.');
  const g = Game.replay(diveFor(sub.board), sub.inputs, b.mapMode);
  if (!g.done || g.done.outcome !== 'exit') return reject('not-home', 'That replay never gets back to the pool.', 422);
  if (!g.done.goal) return reject('no-goal', 'That replay never reaches the end chamber.', 422);
  return { ok: true, board: sub.board, seed: b.seed, gas: Math.round(g.gas * 100) / 100, ticks: g.tick, time: Math.round(g.tick * STEP * 10) / 10 };
}

/** More gas left is better, then a quicker dive; ties go to whoever set it first. */
export function compareScores(a, b) {
  if (a.gas !== b.gas) return b.gas - a.gas;
  if (a.ticks !== b.ticks) return a.ticks - b.ticks;
  if (a.createdAt !== b.createdAt) return a.createdAt < b.createdAt ? -1 : 1;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}
