#!/usr/bin/env python3
"""Late: bundle the game's fonts so nothing depends on the player's system.

Collects every character the game can draw (all text in src/, index.html and
styles.css, which includes every morpheme the station-name generator can
use), asks Google Fonts for subsets of three OFL fonts containing exactly
those characters, and writes them to assets/fonts/ with a fonts.css of
@font-face rules and the licences. Then checks that every non-ASCII
character in the code is covered by at least one bundled font.

    python3 tools/build_fonts.py            (needs network and fonttools)

Re-run it whenever you add text with new characters.
"""
import glob
import io
import os
import re
import sys
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'fonts')
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

# (family, axis spec, file slug, OFL licence path in github.com/google/fonts)
FONTS = [
    ('Inter', 'ital,wght@0,400..900;1,700..900', 'inter', 'ofl/inter/OFL.txt'),
    ('Pixelify Sans', 'wght@400..700', 'pixelify-sans', 'ofl/pixelifysans/OFL.txt'),
    ('Noto Sans SC', 'wght@400..900', 'noto-sans-sc', 'ofl/notosanssc/OFL.txt'),
]


def is_cjk(c):
    o = ord(c)
    return 0x2E80 <= o <= 0x9FFF or 0xF900 <= o <= 0xFAFF or 0xFF00 <= o <= 0xFFEF or 0x3000 <= o <= 0x303F


def is_emoji(c):
    o = ord(c)
    return o >= 0x1F000 or 0x2600 <= o <= 0x27BF and c not in '✓✕✗' or c in '‍️'


def used_chars():
    files = glob.glob(os.path.join(ROOT, 'src', '**', '*.js'), recursive=True)
    files += [os.path.join(ROOT, 'index.html'), os.path.join(ROOT, 'styles.css')]
    chars = set()
    for f in files:
        if f.endswith('atlas.js'):
            continue
        with open(f, encoding='utf8') as fh:
            chars |= set(fh.read())
    ascii_ = ''.join(chr(c) for c in range(0x20, 0x7F))
    emoji = sorted(c for c in chars if is_emoji(c))
    if emoji:
        # emoji come from whatever emoji font the system has, if any: use text instead
        print('emoji in the game text:', ' '.join(f'{c} U+{ord(c):04X}' for c in emoji))
        sys.exit(1)
    extra = sorted(c for c in chars if ord(c) > 0x7E and c.isprintable())
    cjk = ''.join(c for c in extra if is_cjk(c))
    symbols = ''.join(c for c in extra if not is_cjk(c))
    return ascii_, symbols, cjk


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode('utf8')


def main():
    ascii_, symbols, cjk = used_chars()
    os.makedirs(OUT, exist_ok=True)
    wanted = {
        'Inter': ascii_ + symbols,
        'Pixelify Sans': ascii_ + symbols,
        'Noto Sans SC': ascii_ + symbols + cjk,
    }
    css_out = ['/* Generated by tools/build_fonts.py: subsets of OFL fonts (see the licences in this folder). */']
    files = []
    for family, axes, slug, licence in FONTS:
        q = urllib.parse.urlencode({'family': f'{family}:{axes}', 'text': wanted[family], 'display': 'swap'})
        css = fetch(f'https://fonts.googleapis.com/css2?{q}')
        for block in re.findall(r'@font-face\s*{[^}]*}', css):
            style = re.search(r'font-style:\s*(\w+)', block).group(1)
            weight = re.search(r'font-weight:\s*([\d ]+);', block).group(1).strip()
            url = re.search(r'url\(([^)]+)\)', block).group(1)
            name = f'{slug}-{style}.woff2'
            with open(os.path.join(OUT, name), 'wb') as fh:
                fh.write(fetch(url, binary=True))
            files.append((family, name))
            css_out.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                f"  font-style: {style};\n"
                f"  font-weight: {weight};\n"
                "  font-display: block;\n"
                f"  src: url('{name}') format('woff2');\n"
                "}"
            )
        with open(os.path.join(OUT, f'OFL-{slug}.txt'), 'w', encoding='utf8') as fh:
            fh.write(fetch(f'https://raw.githubusercontent.com/google/fonts/main/{licence}'))
    with open(os.path.join(OUT, 'fonts.css'), 'w', encoding='utf8') as fh:
        fh.write('\n'.join(css_out) + '\n')

    # every character we draw must be in one of the bundled fonts
    from fontTools.ttLib import TTFont
    covered = set()
    for _, name in files:
        f = TTFont(os.path.join(OUT, name))
        covered |= set(f.getBestCmap().keys())
    missing = [c for c in symbols + cjk if ord(c) not in covered]
    total = sum(os.path.getsize(os.path.join(OUT, n)) for _, n in files)
    print(f'{len(files)} font files, {total // 1024} KB; {len(cjk)} CJK characters, {len(symbols)} symbols')
    if missing:
        print('NOT COVERED by any bundled font:', ' '.join(f'{c} U+{ord(c):04X}' for c in missing))
        sys.exit(1)
    print('every character the game draws is covered')
    # the tests check that the code never uses a character outside this list
    with open(os.path.join(OUT, 'charset.txt'), 'w', encoding='utf8') as fh:
        fh.write(symbols + cjk + '\n')


if __name__ == '__main__':
    main()
